[project]
name = "Bitcoin-Atomic-swap"
authors = []
description = ""
telemetry = true
requirements = []
[contracts.Bitcoin_atomic_swap-contract]
path = "contracts/Bitcoin_atomic_swap-contract.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
